version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd react_front_end
      - npm install
      - npm install react-plotly.js plotly.js
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ..
      - chmod +x build_and_copy.sh
      - ./build_and_copy.sh
artifacts:
  files:
    - '**/*'
  base-directory: .
