version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd react_front_end
      - npm install
      - npm install react-plotly.js plotly.js
  build:
    commands:
      - |
        if git diff --quiet --exit-code react_front_end; then
          echo "No changes in react_front_end directory. Skipping npm install."
        else
          echo Build started on `date`
          npm run build
        fi
  post_build:
    commands:
      - |
        if git diff --quiet --exit-code react_front_end; then
          echo "No changes in react_front_end directory. Skipping post build."
        else
          echo Build completed on `date`
          cd ..
          chmod +x build_and_copy.sh
          ./build_and_copy.sh
artifacts:
  files:
    - '**/*'
  base-directory: .
