version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd react_front_end
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - cd ..
      - echo Build completed on `date`
      - chmod +x ../build_and_copy.sh
      - ../build_and_copy.sh
artifacts:
  files:
    - '**/*'
  base-directory: Django_back_end/static